### ISSUE TITLE
Weekly Scrum (Week 2)

### ISSUE THREAD

**Issue by adhambadawi** [adhambadawi/mini-survey-monkey#16]
Team Member Updates: - 

Each member answers:
1.   What have I done this week?
2.   What will I do next week?
3.   What is holding me back?

Include Links:
- Reference relevant issues or pull requests.

**Comment by jadensutton** [comment]
1. Added functionality for filling out surveys and filling responses for open-ended and numeric questions
2. Add functionality for multiple choice questions and add CSS styling to improve UI
3. Nothing at the moment

**Comment by AliEl-Khatib** [comment]
1. Added functionality for survey creation supporting open-ended, multiple choice, and numeric questions https://github.com/adhambadawi/mini-survey-monkey/issues/8
2. Add a "remove-option" button for MCQ, and Improve UI to be more user friendly
3. N/A

**Comment by AmrAbdelazeem2** [comment]
1- Added the functionality for displaying the results of a survey, for the open-ended, and number within a range, and the functionality to only allow the survey creator to view the results. #11  
2- Add the compilation and display for the multiple choices questions, and improve the UI for a better user experience.
3- Nothing at the moment

**Comment by yasmina-younes** [comment]
1. Wrote Unit Tests for all models
    UML diagram
    Relational Database schema 
    Readme
2. ---
3. ---

**Comment by adhambadawi** [comment]
1. Initial repo setup with the Kanban Board #1 and #2 . Azure setup and integration with Github Actions #4 #5 . Database Implementation #7 . User Authentication and Authorization #19 .
2. Finish implementing the Survey Closure Mechanism and the Logout mechanism.
3. Nothing at the moment.
